# Generated by Django 5.2.6 on 2025-09-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Car", "0003_remove_car_state_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[("seller", "Seller"), ("buyer", "Buyer")], max_length=10
            ),
        ),
    ]
